Day 2/test-rails/testblog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  resources :authors
  resources :posts
  

  # specific routes to fully support post commenting 
  get '/comments/new/:post_id', to: 'comments#new', as: :new_comment
  post '/comment', to: 'comments#create'

  # get '/authors', to: 'authors#index', as: :authors
  # get '/authors/:id', to: 'authors#show', as: :author
  # get '/author/new', to: 'authors#new', as: :new_author
end

Day 2/test-rails/testblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Day 2/test-rails/testblog/app/models/author.rb
class Author < ActiveRecord::Base
  #has_many :author_posts
  #has_many :posts, through: :author_posts
  before_validation :default_age

  has_many :posts
  
  validates :name, presence: true, length: { in: 3..20}
  validates :surname, presence: true, length: { maximum: 30 }
  validates :age, :inclusion => 1..150

  # for testing
  scope :old, -> { where('age > 30') }
  scope :young, -> { where('age < 20') }


  

  def fullname
    "#{name} #{surname}"
  end

  def default_age 
    self.age = 25 unless age
  end

end

Day 2/test-rails/testblog/app/models/author_post.rb
class AuthorPost < ActiveRecord::Base
    belongs_to :author
    belongs_to :post
end

Day 2/test-rails/testblog/app/models/comment.rb
class Comment < ActiveRecord::Base
   belongs_to :post
   
   has_many :comment_commentators
   has_many :commentators, through: :comment_commentators

   validates :content, presence: true

   #scope :fresh_comments, -> { where('created_at < ?', 10.minutes.ago }

end

Day 2/test-rails/testblog/app/models/comment_commentator.rb
class CommentCommentator < ActiveRecord::Base
    belongs_to :comment
    belongs_to :commentator 
end

Day 2/test-rails/testblog/app/models/commentator.rb
class Commentator < ActiveRecord::Base
    has_many :comment_commentators
    has_many :comments, through: :comment_commentators 

 end

Day 2/test-rails/testblog/app/models/post.rb
class Post < ActiveRecord::Base
   #has_many :author_posts
   #has_many :authors, through: :author_posts
    belongs_to :author
    has_many :comments, dependent: :destroy

   validates :title, :content, presence: true 
   validates :title, uniqueness: true 
   validates :title, length: {maximum: 80}
   validates :content, length: { in: 10..500 }
   
   scope :old, -> { where('created_at < ?', 40.minutes.ago) }

   # call backs -> before i after
#   before_create :annotate_author 

#    def annotate_author
#         self.author = "#{author} from BinarApps"
#    end
end

Day 2/test-rails/testblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

Day 2/test-rails/testblog/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController 
    
    def index 
        @authors = Author.all
    end

    def show 
         @author = Author.find(params[:id])
    end

    def new
        @author = Author.new
    end

    def create 
        @author = Author.new(author_params)
        if @author.save 
            # redirect_to pozostanie w kontekscie -> @author 
            redirect_to authors_path, notice: 'Author was created!'
        else
           render :new
        end
    end

    def edit
        @author = Author.find(params[:id])
    end

    def update 
        @author = Author.find(params[:id])
        if @author.update(author_params) 
            # redirect_to pozostanie w kontekscie -> @author 
            redirect_to authors_path, notice: 'Author was updated!'
        else
           render :edit
        end
    end

    def destroy 
        @author = Author.find(params[:id])        
        @author.destroy
        redirect_to authors_path, alert: 'Author was destroyed!'
    end

    private

        def author_params
            params.require(:author).permit(:name, :surname, :age)
        end
end

Day 2/test-rails/testblog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController 

    def new
       @comment = Comment.new
       # ??? 
       @post_id = params[:post_id]
    end

    def create 
        @comment = Comment.new(comment_params)
        
        if @comment.save 
            redirect_to posts_path, notice: 'You commented successfully!'
        else
           render :new
        end
    end

    private 
        def comment_params
            params.require(:comment).permit(:content, :post_id)
        end

end

Day 2/test-rails/testblog/app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def welcome 
    end

end

Day 2/test-rails/testblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController 
    def index 
        @posts = Post.all
    end

    def show 
         post_id = params[:id]
         @post = Post.find(post_id)
         @post_comments = Comment.where(post_id: post_id)
    end

    def new
        @post = Post.new
        @authors_list = Author.all.map{ |t| [t.name, t.id] }
    end

    def create 
        @post = Post.new(post_params)
        @authors_list = Author.all.map{ |t| [t.name, t.id] }

        if @post.save 
            # redirect_to pozostanie w kontekscie -> @author 
            redirect_to posts_path, notice: 'Post was created!'
        else
           render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
        @authors_list = Author.all.map{ |t| [t.name, t.id] }
    end

    def update 
        @post = Post.find(params[:id])
        @authors_list = Author.all.map{ |t| [t.name, t.id] }

        if @post.update(post_params) 
            # redirect_to pozostanie w kontekscie -> @author 
            redirect_to posts_path, notice: 'Post was updated!'
        else
           render :edit
        end
    end

    def destroy 
        @post = Post.find(params[:id])        
        @post.destroy
        redirect_to posts_path, alert: 'Post was destroyed!'
    end

    private

        def post_params
            params.require(:post).permit(:title, :content, :author_id)
        end
end

Day 2/test-rails/testblog/app/helpers/application_helper.rb
module ApplicationHelper
end

Day 2/test-rails/testblog/app/views/authors/_form.erb
<%= form_for @author do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <hr />
    <%= f.label :surname %>
    <%= f.text_field :surname%>
   <hr />
    <%= f.label :age %>
    <%= f.number_field :age %>
    <hr />
    <hr />
    <%= f.submit 'Save'%>
<% end %>

Day 2/test-rails/testblog/app/views/authors/edit.html.erb
<h1>Edit user: </h1>

<%= render 'form' %>

Day 2/test-rails/testblog/app/views/authors/index.html.erb
<h1>List of all authors</h1>
    <ul>
        <% @authors.each do |author| %>
            <li>
                <%= link_to author.fullname, author_path(id: author.id)  %>
                <%= link_to 'edit', edit_author_path(id: author.id) %>
                <%= link_to 'delete', author_path(id: author.id), method: :delete, data: {confirm: 'Are you sure?'} %>
            </li>
        <% end %>
    </ul>
    
    <hr />
    <%= link_to 'New author', new_author_path %>

Day 2/test-rails/testblog/app/views/authors/new.html.erb
<% if @author.errors.any?%>
    <ul>
         <% @author.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
    </ul>
<% end %>
<h1><Add new author:</h1>
<%= render 'form' %>

Day 2/test-rails/testblog/app/views/authors/show.html.erb
<h1><%= @author.fullname %></h1>
<p>
    Name: 
        <%= @author.name %>
        <hr />
    Surname: 
        <%= @author.surname %> 
        <hr />
    Age:
        <%= @author.age %>
        <hr />
    Created at:
        <%= @author.created_at %>
        <hr />
        <%= link_to 'To posts', posts_path %>
        <%= link_to 'To authors', authors_path %>
</p>

Day 2/test-rails/testblog/app/views/comments/_form.erb
<%= form_for @comment, url: comment_path(@comment) do |f| %>
    <hr/>
    <%= f.label :content %>
    <%= f.text_area :content, cols: 20, rows: 10 %>
    <hr/>
    <%= f.hidden_field :post_id, value: @post_id  %>
    <%= f.submit 'Save'%>
<% end %>

<!-- https://stackoverflow.com/questions/14740702/form-for-undefined-method-user-path -->

Day 2/test-rails/testblog/app/views/comments/new.html.erb
<%= render 'form' %>

Day 2/test-rails/testblog/app/views/home/welcome.html.erb
<h1>Welcome!</h1>
<hr>
<div>
    <p>kfmpsbdfjkops okr[rk [p\q3wkmv [opwkmfcp3m2sbfpn</p>
</div>

Day 2/test-rails/testblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/partials/navbar'%>
    <%= render 'layouts/partials/flash'%>

    <%= yield %>
    
  </body>
</html>

Day 2/test-rails/testblog/app/views/layouts/partials/_flash.erb
  <% if alert %>
    <%= alert %>
  <% end %>

  <% if notice %>
    <%= notice %>
  <% end %>

Day 2/test-rails/testblog/app/views/layouts/partials/_navbar.erb
 <div>
      <%= link_to 'Authors', authors_path %>
      <%= link_to 'Home', root_path %>  
      <%= link_to 'Posts', posts_path %>  
</div>

Day 2/test-rails/testblog/app/views/posts/_form.erb
<%= form_for @post do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <hr />
    <%= f.label :content %>
    <%= f.text_area :content, cols: 20, rows: 10 %>
   <hr />
     <%= f.label :author_id %>
    <%= f.select :author_id,  @authors_list %>
    <hr />
    <%= f.submit 'Save'%>
<% end %>

Day 2/test-rails/testblog/app/views/posts/edit.html.erb
<h1>Edit post: </h1>

<%= render 'form' %>

Day 2/test-rails/testblog/app/views/posts/index.html.erb
<h1>List of all posts</h1>
    <ul>
        <% @posts.each do |post| %>
            <li>
                <%= link_to post.title, post_path(id: post.id)  %>
                <%= link_to 'edit', edit_post_path(id: post.id) %>
                <%= link_to 'delete', post_path(id: post.id), method: :delete, data: {confirm: 'Are you sure?'} %>
                <%= link_to 'Author', author_path(id: post.author_id)  %>
            </li>
        <% end %>
    </ul>
    
    <hr />
    <%= link_to 'New post', new_post_path %>

Day 2/test-rails/testblog/app/views/posts/new.html.erb
<% if @post.errors.any?%>
    <ul>
         <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
    </ul>
<% end %>
<h1><Add new post:</h1>
<%= render 'form' %>

Day 2/test-rails/testblog/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>
    Title: 
        <%= @post.title %>
        <hr />
    Surname: 
        <%= @post.content %> 
        <hr />

        <%= link_to 'Back to posts', posts_path %>
        <!-- TODO: change this to render dynamically - REACT? :)  -->
        <%= link_to 'Comment this post', new_comment_path(post_id: @post.id) %>
</p>
<h2> Post comments: </h2>
<% if @post_comments.any? %>
    <ul>
        <% @post_comments.each do |comment| %>
                <li><%= comment.content %></li>
        <% end %>
    </ul>    
<% end %>